openapi: 3.0.1
info:
  title: API for Football Competition Management 
  description: API for managing football competitions, teams, and players
  version: 1.0.0

servers:
  - url: https://api.football-competition.com/v14

paths:
  /competitions:
    post:
      summary: Create new competition
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompetitionCreateRequest'
      responses:
        '201':
          description: Creation of competition succeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompetitionResponse'
    
    get:
      summary: Get competition's list
      parameters:
        - in: query
          name: page
          required: true
          schema:
            type: integer
          description: The page number to retrieve
        - in: query
          name: pageSize
          required: true
          schema:
            type: integer
          description: The number of items per page
      responses:
        '200':
          description: A list of competitions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CompetitionResponse'

  /teams:
    post:
      summary: Create a new team
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TeamCreateRequest'
      responses:
        '201':
          description: Team created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TeamResponse'
    
    get:
      summary: Get a list of teams
      parameters:
        - in: query
          name: page
          required: true
          schema:
            type: integer
          description: The page number to retrieve
        - in: query
          name: pageSize
          required: true
          schema:
            type: integer
          description: The number of items per page
        - in: query
          name: teamName
          schema:
            type: string
          description: Filter teams by name
      responses:
        '200':
          description: A list of teams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TeamResponse'

  /teams/{teamId}/players:
    post:
      summary: Create a new player for a team
      parameters:
        - in: path
          name: teamId
          required: true
          schema:
            type: integer
          description: The ID of the team
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlayerCreateRequest'
      responses:
        '201':
          description: Player created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerResponse'
    
    get:
      summary: Get a list of players in a team
      parameters:
        - in: path
          name: teamId
          required: true
          schema:
            type: integer
          description: The ID of the team
        - in: query
          name: page
          required: true
          schema:
            type: integer
          description: The page number to retrieve
        - in: query
          name: pageSize
          required: true
          schema:
            type: integer
          description: The number of items per page
        - in: query
          name: playerName
          schema:
            type: string
          description: Filter players by name
      responses:
        '200':
          description: A list of players
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PlayerResponse'

  /teams/{teamId}/competitions:
    post:
      summary: Associate a team with competitions
      parameters:
        - in: path
          name: teamId
          required: true
          schema:
            type: integer
          description: The ID of the team
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: integer
              description: List of competition IDs to associate with the team
      responses:
        '204':
          description: Team associated with competitions successfully

  /teams/{teamId}/players/transfer:
    post:
      summary: Transfer players to a team
      parameters:
        - in: path
          name: teamId
          required: true
          schema:
            type: integer
          description: The ID of the team
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: integer
              description: List of player IDs to associate with the team
      responses:
        '204':
          description: Players transferred successfully

components:
  schemas:
    CompetitionCreateRequest:
      type: object
      properties:
        name:
          type: string
          description: The name of the competition
        location:
          type: string
          description: The country or continent where the competition takes place
      required:
        - name
        - location

    CompetitionResponse:
      type: object
      properties:
        id:
          type: integer
          description: The unique ID of the competition
        name:
          type: string
          description: The name of the competition
        location:
          type: string
          description: The country or continent where the competition takes place

    TeamCreateRequest:
      type: object
      properties:
        name:
          type: string
          description: The name of the team
        slogan:
          type: string
          description: The slogan of the team
      required:
        - name
        - slogan

    TeamResponse:
      type: object
      properties:
        id:
          type: integer
          description: The unique ID of the team
        name:
          type: string
          description: The name of the team
        slogan:
          type: string
          description: The slogan of the team
        competitions:
          type: array
          items:
            $ref: '#/components/schemas/CompetitionResponse'
          description: The list of competitions the team is participating in
        players:
          type: array
          items:
            $ref: '#/components/schemas/PlayerResponse'
          description: The list of players in the team

    PlayerCreateRequest:
      type: object
      properties:
        name:
          type: string
          description: The name of the player
        number:
          type: integer
          description: The player's jersey number
        strongFoot:
          type: string
          description: The player's strong foot
          enum:
            - Left
            - Right
      required:
        - name
        - number
        - strongFoot

    PlayerResponse:
      type: object
      properties:
        id:
          type: integer
          description: The unique ID of the player
        name:
          type: string
          description: The name of the player
        number:
          type: integer
          description: The player's jersey number
        strongFoot:
          type: string
          description: The player's strong foot
